name: icon_font_generator
version: 4.0.0
description: >-
  Converts SVG icons to OTF font and generates Flutter-compatible class.
  Provides an API and a CLI tool.
homepage: https://github.com/ScerIO/icon_font_generator

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  args: ^2.6.0
  collection: ^1.19.1
  dart_style: ^3.0.1
  logger: ^2.5.0
  meta: ^1.16.0
  path: ^1.9.1
  path_parsing: ^1.1.0
  pub_semver: ^2.1.5
  recase: 4.1.0
  vector_math: 2.1.4
  xml: ^6.5.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  
executables:
  generator: generator